image: golang:latest  

stages:
  - test
  - build

format:
  stage: test
  tags:
    - linux

  script:
    - cd src
    - go fmt $(go list ./... | grep -v /vendor/)
    - go get github.com/Syfaro/telegram-bot-api
    - go get github.com/lib/pq
    - go fmt *.go
    - go vet *.go
    - go test -race *.go

compile:
  stage: build
  tags:
    - linux

  script:
    - cd prototype
    - go build -o tg_bot .
  artifacts:
    paths:
      - tg_bot
    expire_in: 1 day
