image: golang:latest  

stages:
  - test
  - build
before_script:
  - cd src/prototype
  - go get github.com/go-telegram-bot-api/telegram-bot-api
  - go get github.com/Syfaro/telegram-bot-api
  - go get github.com/lib/pq
  - go get github.com/skip2/go-qrcode

format:
  stage: test
  tags:
    - linux
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)


compile:
  stage: build
  tags:
    - linux

  script:
    - go build -o tg_bot .
  artifacts:
    paths:
      - src/prototype/tg_bot
    expire_in: 1 day
