image: golang:latest  

stages:
  - test
  - build

format:
  stage: test
  tags:
    - docker

  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  tags:
    - docker

  script:
    - mkdir -p prototype
    - go build -o tg_bot ./...
  artifacts:
    paths:
      - tg_bot
