image: golang:latest  

stages:
  - test
  - build

format:
  stage: test
  tags:
    - linux

  script:
    - cd src/prototype
    - go fmt *.go
    - go vet *.go
    - go test -race *.go

compile:
  stage: build
  tags:
    - linux

  script:
    - cd prototype
    - go build -o tg_bot .
  artifacts:
    paths:
      - tg_bot
    expire_in: 1 day
